import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

export const metadata = { title: 'About PulseAfrica' }

export default function AboutPage() {
  return (
    <>
      <Navbar lang="en" />
      <div style={{ maxWidth:800, margin:'0 auto', padding:'80px 40px', position:'relative', zIndex:10 }}>
        <h1 style={{ fontFamily:"'Cormorant',serif", fontWeight:300, fontSize:'clamp(48px,6vw,72px)', color:'var(--ink)', lineHeight:.95, letterSpacing:-1.5, marginBottom:32 }}>
          About<br/><em style={{ background:'linear-gradient(135deg,var(--amber),var(--amber2))', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent' }}>PulseAfrica</em>
        </h1>

        <div className="article-body">
          <p>PulseAfrica is Africa's first fully autonomous AI-powered news publication. Our mission is to ensure every story that matters to African citizens — from Kigali to Lagos, from Cairo to Cape Town — is covered with depth, accuracy and context.</p>

          <h2>How It Works</h2>
          <p>Our AI engine monitors over 847 news sources across all 54 African nations, 24 hours a day, 7 days a week. Every six hours, the engine identifies the most significant developments in Politics, Sports, Entertainment, Technology, Business and pan-African affairs.</p>
          <p>For each story, our AI writes a comprehensive article averaging 600 words — then automatically translates and adapts it for English, French and Kinyarwanda audiences, ensuring cultural nuance is preserved in each language.</p>

          <h2>Our Languages</h2>
          <p><strong>English</strong> — Professional, authoritative reporting in the style of BBC Africa and Reuters Africa, serving English-speaking audiences across Eastern and Southern Africa and beyond.</p>
          <p><strong>Français</strong> — Natural French journalism in the tradition of RFI and Le Monde Afrique, serving Francophone West and Central Africa.</p>
          <p><strong>Ikinyarwanda</strong> — Original Kinyarwanda articles written for Rwandan readers, not translations, capturing the voice and context of local journalism.</p>

          <h2>Editorial Standards</h2>
          <p>All articles are generated by Claude AI (Anthropic) and are clearly labeled as AI-generated content. PulseAfrica does not publish misinformation and our AI is instructed to write balanced, factual reporting. When in doubt, we err on the side of caution.</p>

          <h2>Contact</h2>
          <p>For advertising inquiries, corrections or partnerships, please reach out via our contact form. PulseAfrica is committed to responsible AI journalism.</p>
        </div>
      </div>
      <Footer />
    </>
  )
}
